server:
  port: 8080

spring:
  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      routes:
        - id: subida-service
          uri: http://localhost:8001
          predicates: 
            - Path=/ingresosSalidas/**
            - Path=/file/**
        - id: justificativo-service
          uri: http://localhost:8002
          predicates:
            - Path=/inasistencia/**
        - id: autorizacion-service
          uri: http://localhost:8003
          predicates:
            - Path=/horaExtra/**
        - id: sueldo-service
          uri: http://localhost:8004
          predicates:
            - Path=/sueldo/**
            - Path=/empleados/**
        - id: complementario-service
          uri: http://localhost:8005
          predicates:
            - Path=/atrasos/**