server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
        routes:
        - id: subida-service         
          uri: http://subida-service:8001
          predicates: 
            - Path=/ingresosSalidas/**
        - id: subida-service        
          uri: http://subida-service:8001
          predicates: 
            - Path=/file/**
        - id: justificativo-service  
          uri: http://justificativo-service:8002
          predicates:
            - Path=/inasistencia/**
        - id: autorizacion-service   
          uri: http://autorizacion-service:8003
          predicates:
            - Path=/horaExtra/**
        - id: sueldo-service         
          uri: http://sueldo-service:8004
          predicates:
            - Path=/sueldo/**
        - id: sueldo-service         
          uri: http://sueldo-service:8004
          predicates:
            - Path=/empleados/**
        - id: sueldo-service
          uri: http://sueldo-service:8004
          predicates:
            - Path=/autenticar/**
        - id: complementario-service 
          uri: http://complementario-service:8005
          predicates:
            - Path=/atrasos/**
 
      # routes:
      #   - id: subida-service         
      #     uri: http://localhost:8001
      #     predicates: 
      #       - Path=/ingresosSalidas/**
      #   - id: subida-service        
      #     uri: http://localhost:8001
      #     predicates: 
      #       - Path=/file/**
      #   - id: justificativo-service  
      #     uri: http://localhost:8002
      #     predicates:
      #       - Path=/inasistencia/**
      #   - id: autorizacion-service   
      #     uri: http://localhost:8003
      #     predicates:
      #       - Path=/horaExtra/**
      #   - id: sueldo-service         
      #     uri: http://localhost:8004
      #     predicates:
      #       - Path=/sueldo/**
      #   - id: sueldo-service         
      #     uri: http://localhost:8004
      #     predicates:
      #       - Path=/empleados/**
      #   - id: sueldo-service
      #     uri: http://localhost:8004
      #     predicates:
      #       - Path=/autenticar/**
      #   - id: complementario-service 
      #     uri: http://localhost:8005
      #     predicates:
      #       - Path=/atrasos/**
