server:
  port: 8080

spring:
  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true 
      routes:
        - id: subida-service         # Funciono
          uri: http://localhost:8001
          predicates: 
            - Path=/ingresosSalidas/**
        - id: subida-service         # NO FUNCIONO
          uri: http://localhost:8001
          predicates: 
            - Path=/file/**
        - id: justificativo-service  # Funciono
          uri: http://localhost:8002
          predicates:
            - Path=/inasistencia/**
        - id: autorizacion-service   # Funciono
          uri: http://localhost:8003
          predicates:
            - Path=/horaExtra/**
        - id: sueldo-service         # Funciono
          uri: http://localhost:8004
          predicates:
            - Path=/sueldo/**
        - id: sueldo-service         # Funciono
          uri: http://localhost:8004
          predicates:
            - Path=/empleados/**
        - id: complementario-service # Funciono
          uri: http://localhost:8005
          predicates:
            - Path=/atrasos/**