server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
        routes:
        - id: subida-service         
          uri: lb://subida-service
          predicates: 
            - Path=/ingresosSalidas/**
        - id: justificativo-service  
          uri: lb://justificativo-service
          predicates:
            - Path=/inasistencia/**
        - id: autorizacion-service   
          uri: lb://autorizacion-service
          predicates:
            - Path=/horaExtra/**
        - id: sueldo-service         
          uri: lb://sueldo-service
          predicates:
            - Path=/sueldos/**
        - id: complementario-service 
          uri: lb://complementario-service
          predicates:
            - Path=/atrasos/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
